### ISSUE TITLE
what's the valid symbol?

### ISSUE THREAD

**Issue by lookis** [JexApi/jex-official-api-docs#11]
seems every symbol is invalid for option klines, such as BTCUSDT, LTCUSDT, JEXUSDT ...
for example: https://www.jex.com/api/v1/option/klines?symbol=BTCUSDT&interval=5m

could you provide a full symbol list api? thx

**Comment by jiaofu** [comment]
it is the  option klines.   what you want  the spot  or contract ?  you will get the  [/api/v1/spot/klines](url) or `/api/v1/contract/klines`.  if you want all  symol. you should get the url  [/api/v1/exchangeInfo](url). if

**Comment by lookis** [comment]
thanks very much, exchangeInfo is very helpful
